;;; Automatically generated by ‘recentf’ on Wed Jun  1 22:00:26 2022.

(setq recentf-list
      '(
        "/home/nmlss/.dotty/link.sh"
        "/sites/holdnack.net/build.sh"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
